apps/gigpillar_web/lib/gigpillar_web/router.ex
defmodule GigpillarWeb.Router do
  use GigpillarWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(GigpillarWeb.Plug.AssignCurrentUser)
    plug(GigpillarWeb.Plug.UserLocation)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(GigpillarWeb.Plug.AssignCurrentUser)
    plug(:put_secure_browser_headers)
  end

  scope "/", GigpillarWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/search", SearchController, :search)

    resources("/gigs", GigController)
  end

  scope "/auth", GigpillarWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    get("/identity/register", AuthController, :register)
    post("/identity/callback", AuthController, :callback)
    post("/identity/register_callback", AuthController, :register_callback)
    post("/logout", AuthController, :delete)
  end

  scope "/api", GigpillarWeb do
    pipe_through(:api)

    get("/autocomplete/location", AutocompleteController, :location)
    get("/autocomplete/artist", AutocompleteController, :artist)
    get("/autocomplete/search", AutocompleteController, :search)
  end
end

apps/gigpillar_web/lib/gigpillar_web/views/layout_view.ex
defmodule GigpillarWeb.LayoutView do
  use GigpillarWeb, :view
end

apps/gigpillar_web/lib/gigpillar_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Gigpillar</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script async type="module" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="<%= if assigns[:page_class] do %>page-<%= assigns[:page_class] %><% end %>">
    <a class="sr-only sr-only-focus skip-to-main" href="#main">Skip to content</a>
    <header class="page-header" role="banner">
      <a href="/" class="brand<%= if assigns[:page_class] == "index" do %> active<% end %>" aria-label="Gig Pillar homepage">Gig Pillar</a>
      <%= form_for @conn, Routes.search_path(@conn, :search), [method: "get", class: "page-search-box"], fn f -> %>
        <label for="search">
          <span class="sr-only">Search for city, artist and concert</span>
        </label>
        <search-box
          inputId="search"
          placeholder="Search for city, artist and concert"
          src="/api/autocomplete/search"
          name="<%= input_name f, :query %>"
          value="<%= input_value f, :query %>">
          <span class="search-icon"></span>
          <input readonly placeholder="Search for city, artist and concert" value="<%= @conn.params["query"] %>">
        </search-box>
      <% end %>
      <nav role="navigation" class="page-navigation">
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/gigs/new">Add Gig</a></li>
          <%= if assigns[:current_user] do %>
            <li><a href="/gigs">My Gigs</a></li>
            <li><span><%= @current_user.username %></span></li>
          <% else %>
            <li><a href="/auth/identity">Login</a></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <main id="main" role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer></footer>
  </body>
</html>